language: python

python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

script: "./runtests"

# nothing to install, but this will squelch a warning
install: "true"

notifications:
  email:
      - travis-ci+python-iptools@bd808.com
